[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.images]
compress = true

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "."
  exclude = [
    "./tools/**",
    "./backups/**",
    "**/*.json"
  ]

[[redirects]]
  from = "/api/pet-profiles/:id"
  to = "/.netlify/functions/get-pet-profile/:id"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
